### ISSUE TITLE
Where I can find StudentAssets.zip?

### ISSUE THREAD

**Issue by KarinaJean** [TryCatchLearn/Skinet3.1#2]
I was trying to find the StudentAssets.zip from  @TryCatchLearn/Skinet in the resources but can't find it. Need help

**Comment by TryCatchLearn** [comment]
Hi Karina,
You can get it from [here](https://trycatchlearn.com/2020/04/18/building-an-inventory-system-for-the-skinet-app-in-the-net-and-angular-course-part-1/) (bottom of the post), or if you are taking this course on Udemy you can get it from the lesson entitled source code and project assets.

**Comment by KarinaJean** [comment]
Thanks a lot Neil :)



Best Regards,

Karina Jean Książek


*e:* karinajean.ksiazek@gmail.com
*m:* +48 574 444 963
