### ISSUE TITLE
Deprecated Redis 64-bit 3.1.0

### ISSUE THREAD

**Issue by arashyazdani** [TryCatchLearn/Skinet3.1#7]
Hi, I went to the Chocolatey website and as you seen the Redis 64-bit 3.1.0 has been deprecated and there are no any new version for use. Do you have any suggestion. I use Windows on my system.

**Comment by arashyazdani** [comment]
How about these links?

https://docs.microsoft.com/en-us/windows/wsl/about

https://github.com/microsoftarchive/redis/releases/tag/win-3.2.100

**Comment by arashyazdani** [comment]
I subscribed your course on Udemy, as you said. But, you didn't answer my question after 5 hours.

**Comment by block0xhash** [comment]
on that Chocolatey page, comments section they recommend  using memurai as a alternative on windows.

also see note from Microsoft here:
https://github.com/MicrosoftArchive/redis

" This project is no longer being actively maintained. If you are looking for a Windows version of Redis, you may want to check out Memurai. Please note that Microsoft is not officially endorsing this product in any way ".

it runs on the same port and all commands are the same

this link is:
https://www.memurai.com/

**Comment by bothwellw** [comment]
but on Chocolatey they do indicate the alternative to use is  memurai in the comments sections. 

Please  be patient. the course is very popular and has a a lot of students.

 its unfair to the instructor to complain that you  didn't get a response within  just 5 hours of posting your question. 

I am even the best companies in the world take  much longer to respond to support emails  :-).

you must also search in the questions area, as some issues you have might  have already be experienced by other students and the solution posted.

and also try to use google, good luck in the course. I am also a student and enjoying it very much.

**Comment by block0xhash** [comment]
> I subscribed your course on Udemy, as you said. But, you didn't answer my question after 5 hours.

you must post your question on Udemy on the Question and Answer section  below each course  vedio.

do not post  on github. 

below each vedio you will see the QnA tab.

  you can search for your question first as another student might already have asked and a solution posted.

 
![Capture](https://user-images.githubusercontent.com/16897613/90695462-c52a6980-e27a-11ea-8b7d-f28ba61855f6.PNG)

**Comment by block0xhash** [comment]
> But, you didn't answer my question after 5 hours.

please be patient with the instructor  :-)
